In [144]:
import numpy as np
import datetime
print(datetime.datetime.now())

2018-11-24 22:24:25.760686


In [145]:
"""
The y=target is to maximize this equation ASAP:
    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best 
    possible values after a number of generations.
"""

'\nThe y=target is to maximize this equation ASAP:\n    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6\n    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)\n    \n    What are the best values for the 6 weights w1 to w6?\n    We are going to use the genetic algorithm for the best \n    possible values after a number of generations.\n'

In [146]:
# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = 6

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""

sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) 
# The population will have sol_per_pop chromosome where each chromosome has num_weights genes.

num_generations = 5

In [147]:
type(equation_inputs)

list

In [148]:
type(pop_size)

tuple

In [149]:
pop_size

(8, 6)

In [150]:
#Creating the initial population.

#new_population = np.random.uniform(low=-4.0, high=4.0, size=pop_size)
#new_population=np.ones(pop_size)
new_population=np.arange(num_weights*sol_per_pop).reshape(pop_size)

In [151]:
print(new_population[0:1])

[[0 1 2 3 4 5]]


In [152]:
print(new_population)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


In [153]:
type(new_population)

numpy.ndarray

In [154]:
new_population.shape

(8, 6)

In [155]:
fitness=np.matmul(new_population,equation_inputs)

In [156]:
fitness

array([ -47.5,  -78.7, -109.9, -141.1, -172.3, -203.5, -234.7, -265.9])

In [157]:
#fitness=np.absolute(fitness)

In [158]:
fitness

array([ -47.5,  -78.7, -109.9, -141.1, -172.3, -203.5, -234.7, -265.9])

In [159]:
maxFitnessIndex=np.argpartition(fitness,4)


In [160]:
maxFitnessIndex

array([4, 7, 6, 5, 3, 1, 2, 0])

In [161]:
parentsIndex=maxFitnessIndex[4:]

In [162]:
parentsIndex

array([3, 1, 2, 0])

In [163]:
fitness[maxFitnessIndex[4:]]

array([-141.1,  -78.7, -109.9,  -47.5])

In [164]:
fitness

array([ -47.5,  -78.7, -109.9, -141.1, -172.3, -203.5, -234.7, -265.9])

In [165]:
maxFitnessIndex2=np.argpartition(fitness,-4)[-4:,]

In [166]:
maxFitnessIndex2

array([3, 1, 2, 0])

In [167]:
parentsIndex=maxFitnessIndex[4:]

In [168]:
parentsIndex

array([3, 1, 2, 0])

In [169]:
parentsIndex

array([3, 1, 2, 0])

In [170]:
np.array('parents')

array('parents',
      dtype='<U7')

In [171]:
new_population[0,]

array([0, 1, 2, 3, 4, 5])

In [172]:
for i in parentsIndex:
    print(i,new_population[i,])

3 [18 19 20 21 22 23]
1 [ 6  7  8  9 10 11]
2 [12 13 14 15 16 17]
0 [0 1 2 3 4 5]


In [173]:
type(new_population[1,1])

numpy.int64

In [174]:
type(parentsIndex[1])

numpy.int64

In [175]:
#parentsIndex=parentsIndex.astype(int)

In [176]:
parents=np.stack(new_population[i,] for i in parentsIndex)

In [177]:
parents

array([[18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5]])

In [204]:
#crossoverPoint=np.random.randint(0,num_weights,100)
crossoverPoint=np.random.randint(0,num_weights,sol_per_pop)

#crossoverPoint=np.random.randint(0,num_weights)

In [205]:
#crossoverPoint=4

In [206]:
crossoverPoint

array([0, 2, 1, 5, 4, 1, 3, 0])

In [207]:
parentsIndex[-4:]

array([3, 1, 2, 0])

In [208]:
mateIndex=(parentsIndex[-4:])

In [209]:
mateIndex

array([3, 1, 2, 0])

In [210]:
parentsIndex

array([3, 1, 2, 0])

In [211]:
mateIndex[1:]

array([1, 2, 0])

In [212]:
parentsIndex

array([3, 1, 2, 0])

In [213]:
#partnerIndex=(np.random.choice(parentsIndex[1:],3,replace=False))

In [214]:
offspring=np.zeros(num_parents_mating*num_weights).reshape(num_parents_mating,num_weights)

In [215]:
offspring

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [216]:
partnerIndex=(np.random.choice(parentsIndex,3,replace=False))

In [217]:
parentsIndex

array([3, 1, 2, 0])

In [218]:
parentsIndex[0]

3

In [219]:
parents

array([[18, 19, 20, 21, 22, 23],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [ 0,  1,  2,  3,  4,  5]])

In [220]:
new_population[3]

array([18, 19, 20, 21, 22, 23])

In [224]:
for i in range (1,num_parents_mating,2):
    
    print("Parents\n")
    print (parentsIndex[i-1],new_population[parentsIndex[i-1]], "\t", \
           parentsIndex[i],new_population[parentsIndex[i]],"\n")
    
    print("Offspring\n")
    
    offspring[i,]=np.concatenate((  
        parents[parentsIndex[i-1],0:crossoverPoint[i]],\
            parents[parentsIndex[i],crossoverPoint[i]:]), \
            axis=0)
    
    #print(parents[parentsIndex[i],0:crossoverPoint])
    #print(parents[parentsIndex[i],crossoverPoint:])    
    
    #print(offspring,"\n")
    print(offspring[i],"\n")
    offspring[i-1]=offspring[i]

Parents

3 [18 19 20 21 22 23] 	 1 [ 6  7  8  9 10 11] 

Offspring

[  0.   1.   8.   9.  10.  11.] 

Parents

2 [12 13 14 15 16 17] 	 0 [0 1 2 3 4 5] 

Offspring

[ 12.  13.  14.  15.  16.  23.] 



In [223]:
"""
for i in range (1,num_parents_mating,2):
    print("Parents\n")
    print (parentsIndex[i-1],parents[parentsIndex[i-1]],"\t",parentsIndex[i],parents[parentsIndex[i]],"\n")
    
    print("Offspring\n")
    
    offspring[i,]=np.concatenate((  
        parents[parentsIndex[i-1],0:crossoverPoint], \
            parents[parentsIndex[i],crossoverPoint:]),   \
            axis=0)
    
    #print(parents[parentsIndex[i],0:crossoverPoint])
    #print(parents[parentsIndex[i],crossoverPoint:])    
    
    #print(offspring,"\n")
    print(offspring[i])
    offspring[i-1]=offspring[i]
"""    
    

'\nfor i in range (1,num_parents_mating,2):\n    print("Parents\n")\n    print (parentsIndex[i-1],parents[parentsIndex[i-1]],"\t",parentsIndex[i],parents[parentsIndex[i]],"\n")\n    \n    print("Offspring\n")\n    \n    offspring[i,]=np.concatenate((  \n        parents[parentsIndex[i-1],0:crossoverPoint],             parents[parentsIndex[i],crossoverPoint:]),               axis=0)\n    \n    #print(parents[parentsIndex[i],0:crossoverPoint])\n    #print(parents[parentsIndex[i],crossoverPoint:])    \n    \n    #print(offspring,"\n")\n    print(offspring[i])\n    offspring[i-1]=offspring[i]\n'

In [197]:
offspring

array([[  0.,   1.,   2.,   3.,  10.,  11.],
       [  0.,   1.,   2.,   3.,  10.,  11.],
       [ 12.,  13.,  14.,  15.,  22.,  23.],
       [ 12.,  13.,  14.,  15.,  22.,  23.]])

In [198]:
offspring[1,0:crossoverPoint]

array([ 0.,  1.,  2.,  3.])

In [199]:
offspring[1,crossoverPoint:]

array([ 10.,  11.])

In [200]:
np.concatenate((offspring[1,0:crossoverPoint],offspring[1,crossoverPoint:]),axis=0)

array([  0.,   1.,   2.,   3.,  10.,  11.])

In [201]:
"""
for generation in range(num_generations):
    print("Generation : ", generation)

    # Measing the fitness of each chromosome in the population.
    fitness = GA.cal_pop_fitness(equation_inputs, new_population)
    #print("fitness=",fitness,"\n")
    
    # Selecting the best parents in the population for mating.
    parents = GA.select_mating_pool(new_population, fitness, 
                                      num_parents_mating)

    # Generating next generation using crossover.
    offspring_crossover = GA.crossover(parents,
                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))

    # Adding some variations to the offsrping using mutation.
    offspring_mutation = GA.mutation(offspring_crossover)

    # Creating the new population based on the parents and offspring.
    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = offspring_mutation

    # The best result in the current iteration.
    print("Best result : ", np.max(np.sum(new_population*equation_inputs, axis=1)))

# Getting the best solution after iterating finishing all generations.
#At first, the fitness is calculated for each solution in the final generation.
fitness = GA.cal_pop_fitness(equation_inputs, new_population)

# Then return the index of that solution corresponding to the best fitness.
best_match_idx = np.where(fitness == np.max(fitness))
"""


'\nfor generation in range(num_generations):\n    print("Generation : ", generation)\n\n    # Measing the fitness of each chromosome in the population.\n    fitness = GA.cal_pop_fitness(equation_inputs, new_population)\n    #print("fitness=",fitness,"\n")\n    \n    # Selecting the best parents in the population for mating.\n    parents = GA.select_mating_pool(new_population, fitness, \n                                      num_parents_mating)\n\n    # Generating next generation using crossover.\n    offspring_crossover = GA.crossover(parents,\n                                       offspring_size=(pop_size[0]-parents.shape[0], num_weights))\n\n    # Adding some variations to the offsrping using mutation.\n    offspring_mutation = GA.mutation(offspring_crossover)\n\n    # Creating the new population based on the parents and offspring.\n    new_population[0:parents.shape[0], :] = parents\n    new_population[parents.shape[0]:, :] = offspring_mutation\n\n    # The best result in the curre

In [202]:
"""
print("Best solution : ", new_population[best_match_idx, :])
print("Best solution fitness : ", fitness[best_match_idx])
"""

'\nprint("Best solution : ", new_population[best_match_idx, :])\nprint("Best solution fitness : ", fitness[best_match_idx])\n'